import type { VizId } from "@/content/types";

export type VizGroup = "JavaScript runtime" | "Go runtime" | "Systems" | "Hardware & memory";

export const VIZ_META: Record<VizId, { title: string; summary: string; group: VizGroup; kind: "trace" | "model"; lessons: string[] }> = {
  "js-closure": { title: "Closures and retained environments", summary: "Step through makeCounter(): watch execution contexts get pushed and popped while the returned function keeps its lexical environment alive on the heap.", group: "JavaScript runtime", kind: "trace", lessons: ["javascript/closures", "javascript/execution-context"] },
  "js-event-loop": { title: "Event loop: tasks vs microtasks", summary: "See why promise callbacks run before setTimeout callbacks: the call stack, Web APIs, the microtask queue and the task queue, step by step.", group: "JavaScript runtime", kind: "trace", lessons: ["javascript/event-loop", "javascript/promises", "javascript/timers"] },
  "js-hoisting": { title: "Hoisting and the temporal dead zone", summary: "The creation phase sets up var (undefined), functions (fully) and let/const (uninitialized). Watch a TDZ ReferenceError happen.", group: "JavaScript runtime", kind: "trace", lessons: ["javascript/hoisting-tdz", "javascript/var-let-const"] },
  "js-this": { title: "How `this` is bound", summary: "Method call, plain call, arrow function, bind and new — the same function gets a different `this` depending on how it is called.", group: "JavaScript runtime", kind: "trace", lessons: ["javascript/this-binding", "javascript/arrow-functions", "javascript/call-apply-bind"] },
  "js-references": { title: "Stack values, heap objects and aliasing", summary: "Primitives are copied; objects are shared by reference. See aliasing, shallow copies and when objects become unreachable.", group: "JavaScript runtime", kind: "trace", lessons: ["javascript/data-types", "javascript/deep-copy", "javascript/memory-leaks-gc"] },
  "js-async-await": { title: "async/await suspension", summary: "An async function runs synchronously until its first await, then suspends; its continuation resumes later as a microtask.", group: "JavaScript runtime", kind: "trace", lessons: ["javascript/async-await", "javascript/promises"] },
  "go-slices": { title: "Slice headers, backing arrays and append", summary: "Watch append grow capacity using Go's real growth formula and size classes, and see two slices alias the same backing array.", group: "Go runtime", kind: "model", lessons: ["go/slices-internals"] },
  "go-channels": { title: "Channels: buffered vs unbuffered", summary: "Send, receive and close on a channel and see the buffer, the queue of blocked senders and receivers, and the panics.", group: "Go runtime", kind: "model", lessons: ["go/channels", "go/channel-close-range", "go/select"] },
  "go-scheduler": { title: "The G/M/P scheduler", summary: "Spawn goroutines, watch Ps run them from local run queues, steal work, hand off on blocking syscalls and preempt long runners.", group: "Go runtime", kind: "model", lessons: ["go/gmp-scheduler", "go/goroutines"] },
  "go-mutex": { title: "Race condition vs mutex", summary: "Interleave two goroutines' load/add/store steps yourself and lose an update — then turn the mutex on and try again.", group: "Go runtime", kind: "model", lessons: ["go/mutex", "go/race-deadlock-livelock"] },
  "go-waitgroup": { title: "WaitGroup", summary: "Add, Done and Wait: how main waits for workers, and what goes wrong when Add is called inside the goroutine.", group: "Go runtime", kind: "trace", lessons: ["go/waitgroup", "go/fork-join"] },
  "go-worker-pool": { title: "Worker pool and backpressure", summary: "A producer, a buffered jobs channel and N workers. Tune workers and buffer size and watch throughput, queueing and a blocked producer.", group: "Go runtime", kind: "model", lessons: ["go/worker-pool", "go/backpressure-bounded-concurrency"] },
  "sys-request-flow": { title: "Life of an HTTPS request", summary: "DNS, TCP, TLS, load balancer, app, cache and database — toggle connection reuse and cache hits and watch the latency budget change.", group: "Systems", kind: "model", lessons: ["system-design/dns-tcp-lb-firewalls", "networks/http"] },
  "sys-cache": { title: "Cache-aside, TTLs and stale reads", summary: "Read and write keys through a cache. See hits, misses, TTL expiry and stale data when invalidation is missing.", group: "Systems", kind: "model", lessons: ["system-design/caching-strategies", "system-design/cache-invalidation"] },
  "sys-load-balancer": { title: "Load-balancing algorithms", summary: "Round robin, least connections and consistent hashing under uneven load — and what happens when a server dies.", group: "Systems", kind: "model", lessons: ["system-design/load-balancing-algorithms"] },
  "sys-rate-limiter": { title: "Token-bucket rate limiter", summary: "Bursts, refill rate and capacity: send requests and see which are allowed and which get 429.", group: "Systems", kind: "model", lessons: ["system-design/rate-limiting"] },
  "sys-circuit-breaker": { title: "Circuit breaker", summary: "Closed, open and half-open: make the dependency fail and watch the breaker trip, shed load and probe for recovery.", group: "Systems", kind: "model", lessons: ["system-design/circuit-breakers-timeouts-retries"] },
  "mem-hierarchy": { title: "Memory hierarchy latency ladder", summary: "Registers to network round trips, in nanoseconds and in human time. Conceptual, order-of-magnitude numbers.", group: "Hardware & memory", kind: "model", lessons: ["os/cpu-memory-hierarchy", "system-design/latency-throughput"] },
};
